apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: existing-single-inrepo-port-ingress-autodeploy-20250819100942
build:
  tagPolicy:
    sha256: {}
  platforms: ["linux/amd64", "darwin/arm64"]
  artifacts:
  - image: ghcr.io/fake-org/fake-registry/existing-single-inrepo-port-ingress-autodeploy-20250819100942
    custom:
      buildCommand: ./build.sh
      dependencies:
        paths:
          - "go.mod"
          - "**/*.go"
manifests:
  kustomize:
    paths:
    - deploy/overlays/dev
profiles:
- name: prod
  manifests:
    kustomize:
      paths:
      - deploy/overlays/prod
